FROM maven:3.8.5-openjdk-17 AS BUILD
COPY ./ipl-dashboard/. .
RUN mvn clean package -DskipTests

FROM openjdk:17.0.1-jdk-slim
COPY --from=build/target/ipl-dashboard-0.0.1-SNAPSHOT.jar demo.jar
EXPOSE 8080
ENTRYPINT ["java","--jar","demo.jar"]